source file: <b>/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/boto3/exceptions.py</b><br>


file stats: <b>47 lines, 29 executed: 61.7% covered</b>
<pre>
<font color="black">   1. # Copyright 2014 Amazon.com, Inc. or its affiliates. All Rights Reserved.</font>
<font color="black">   2. #</font>
<font color="black">   3. # Licensed under the Apache License, Version 2.0 (the &quot;License&quot;). You</font>
<font color="black">   4. # may not use this file except in compliance with the License. A copy of</font>
<font color="black">   5. # the License is located at</font>
<font color="black">   6. #</font>
<font color="black">   7. # http://aws.amazon.com/apache2.0/</font>
<font color="black">   8. #</font>
<font color="black">   9. # or in the &quot;license&quot; file accompanying this file. This file is</font>
<font color="black">  10. # distributed on an &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR CONDITIONS OF</font>
<font color="black">  11. # ANY KIND, either express or implied. See the License for the specific</font>
<font color="black">  12. # language governing permissions and limitations under the License.</font>
<font color="black">  13. </font>
<font color="black">  14. # All exceptions in this class should subclass from Boto3Error.</font>
<font color="green">  15. import botocore.exceptions</font>
<font color="black">  16. </font>
<font color="black">  17. </font>
<font color="black">  18. # All exceptions should subclass from Boto3Error in this module.</font>
<font color="green">  19. class Boto3Error(Exception):</font>
<font color="green">  20.     &quot;&quot;&quot;Base class for all Boto3 errors.&quot;&quot;&quot;</font>
<font color="black">  21. </font>
<font color="black">  22. </font>
<font color="green">  23. class ResourceLoadException(Boto3Error):</font>
<font color="green">  24.     pass</font>
<font color="black">  25. </font>
<font color="black">  26. </font>
<font color="black">  27. # NOTE: This doesn't appear to be used anywhere.</font>
<font color="black">  28. # It's probably safe to remove this.</font>
<font color="green">  29. class NoVersionFound(Boto3Error):</font>
<font color="green">  30.     pass</font>
<font color="black">  31. </font>
<font color="black">  32. </font>
<font color="black">  33. # We're subclassing from botocore.exceptions.DataNotFoundError</font>
<font color="black">  34. # to keep backwards compatibility with anyone that was catching</font>
<font color="black">  35. # this low level Botocore error before this exception was</font>
<font color="black">  36. # introduced in boto3.</font>
<font color="black">  37. # Same thing for ResourceNotExistsError below.</font>
<font color="green">  38. class UnknownAPIVersionError(Boto3Error,</font>
<font color="green">  39.                              botocore.exceptions.DataNotFoundError):</font>
<font color="green">  40.     def __init__(self, service_name, bad_api_version,</font>
<font color="black">  41.                  available_api_versions):</font>
<font color="black">  42.         msg = (</font>
<font color="red">  43.             &quot;The '%s' resource does not an API version of: %s\n&quot;</font>
<font color="black">  44.             &quot;Valid API versions are: %s&quot;</font>
<font color="red">  45.             % (service_name, bad_api_version, available_api_versions)</font>
<font color="black">  46.         )</font>
<font color="black">  47.         # Not using super because we don't want the DataNotFoundError</font>
<font color="black">  48.         # to be called, it has a different __init__ signature.</font>
<font color="red">  49.         Boto3Error.__init__(self, msg)</font>
<font color="black">  50. </font>
<font color="black">  51. </font>
<font color="green">  52. class ResourceNotExistsError(Boto3Error,</font>
<font color="green">  53.                              botocore.exceptions.DataNotFoundError):</font>
<font color="green">  54.     &quot;&quot;&quot;Raised when you attempt to create a resource that does not exist.&quot;&quot;&quot;</font>
<font color="green">  55.     def __init__(self, service_name, available_services, has_low_level_client):</font>
<font color="black">  56.         msg = (</font>
<font color="red">  57.             &quot;The '%s' resource does not exist.\n&quot;</font>
<font color="black">  58.             &quot;The available resources are:\n&quot;</font>
<font color="red">  59.             &quot;   - %s\n&quot; % (service_name, '\n   - '.join(available_services))</font>
<font color="black">  60.         )</font>
<font color="red">  61.         if has_low_level_client:</font>
<font color="red">  62.             msg += (</font>
<font color="red">  63.                 &quot;\nConsider using a boto3.client('%s') instead &quot;</font>
<font color="red">  64.                 &quot;of a resource for '%s'&quot; % (service_name, service_name))</font>
<font color="black">  65.         # Not using super because we don't want the DataNotFoundError</font>
<font color="black">  66.         # to be called, it has a different __init__ signature.</font>
<font color="red">  67.         Boto3Error.__init__(self, msg)</font>
<font color="black">  68. </font>
<font color="black">  69. </font>
<font color="green">  70. class RetriesExceededError(Boto3Error):</font>
<font color="green">  71.     def __init__(self, last_exception, msg='Max Retries Exceeded'):</font>
<font color="red">  72.         super(RetriesExceededError, self).__init__(msg)</font>
<font color="red">  73.         self.last_exception = last_exception</font>
<font color="black">  74. </font>
<font color="black">  75. </font>
<font color="green">  76. class S3TransferFailedError(Boto3Error):</font>
<font color="green">  77.     pass</font>
<font color="black">  78. </font>
<font color="black">  79. </font>
<font color="green">  80. class S3UploadFailedError(Boto3Error):</font>
<font color="green">  81.     pass</font>
<font color="black">  82. </font>
<font color="black">  83. </font>
<font color="green">  84. class DynamoDBOperationNotSupportedError(Boto3Error):</font>
<font color="green">  85.     &quot;&quot;&quot;Raised for operantions that are not supported for an operand&quot;&quot;&quot;</font>
<font color="green">  86.     def __init__(self, operation, value):</font>
<font color="black">  87.         msg = (</font>
<font color="red">  88.             '%s operation cannot be applied to value %s of type %s directly. '</font>
<font color="black">  89.             'Must use AttributeBase object methods (i.e. Attr().eq()). to '</font>
<font color="black">  90.             'generate ConditionBase instances first.' %</font>
<font color="red">  91.             (operation, value, type(value)))</font>
<font color="red">  92.         Exception.__init__(self, msg)</font>
<font color="black">  93. </font>
<font color="black">  94. # FIXME: Backward compatibility</font>
<font color="green">  95. DynanmoDBOperationNotSupportedError = DynamoDBOperationNotSupportedError</font>
<font color="black">  96. </font>
<font color="black">  97. </font>
<font color="green">  98. class DynamoDBNeedsConditionError(Boto3Error):</font>
<font color="green">  99.     &quot;&quot;&quot;Raised when input is not a condition&quot;&quot;&quot;</font>
<font color="green"> 100.     def __init__(self, value):</font>
<font color="black"> 101.         msg = (</font>
<font color="red"> 102.             'Expecting a ConditionBase object. Got %s of type %s. '</font>
<font color="black"> 103.             'Use AttributeBase object methods (i.e. Attr().eq()). to '</font>
<font color="red"> 104.             'generate ConditionBase instances.' % (value, type(value)))</font>
<font color="red"> 105.         Exception.__init__(self, msg)</font>
<font color="black"> 106. </font>
<font color="black"> 107. </font>
<font color="green"> 108. class DynamoDBNeedsKeyConditionError(Boto3Error):</font>
<font color="green"> 109.     pass</font>
</pre>

